apiVersion: apps/v1
kind: Deployment
metadata:
  name: cic-vpx
spec:
  selector:
    matchLabels:
      app: cic-vpx
  replicas: 1
  template:
    metadata:
      name: cic-vpx
      labels:
        app: cic-vpx
      annotations:
    spec: 
      serviceAccountName: frontenddeveloper-cpx
      containers:
      - name: cic-vpx
        image: "quay.io/citrix/citrix-k8s-ingress-controller:1.30.1"
        env:
         # Set NetScaler NSIP/SNIP, SNIP in case of HA (mgmt has to be enabled) 
         - name: "NS_IP"
           value: "10.105.158.148"
         - name: "NS_PROTOCOL"
           value: "HTTPS"
         - name: "NS_PORT"
           value: "443" 
         # Set username for Nitro
         - name: "NS_USER"
           valueFrom:
            secretKeyRef:
             name: nslogin
             key: username
         # Set user password for Nitro
         - name: "NS_PASSWORD"
           valueFrom:
            secretKeyRef:
             name: nslogin
             key: password
         # Set log level
         - name: "EULA"
           value: "yes"
         - name: "NS_APPS_NAME_PREFIX"
           value: "app1"
         - name: "SCOPE"
           value: "local"
        args:
          - --ingress-classes
            cic-vpx-frontend
          - --feature-node-watch
            true
        imagePullPolicy: Always