apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-vpx
  annotations:
   kubernetes.io/ingress.class: "cic-vpx-mobile"
   ingress.citrix.com/insecure-termination: "redirect"
   ingress.citrix.com/frontend-ip: "10.105.158.197"
   ingress.citrix.com/secure_backend: '{"lb-service-mobile": "True"}'
spec:
  tls:
  - secretName: mobile-secret
  rules:
  - host:  mobile.agiledevelopers.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lb-service-mobile
            port:
              number: 443